Add request spec coverage for unspam. Currently failing with `NoMethodError:        undefined method `deliver_comment_notification' for #<Comment:0x00007f85444f66d8>`... Not sure if i'm missing something... it's failing in development as well.